### ISSUE TITLE
uint buyPrice = 10000

### ISSUE THREAD

**Issue by egorzaremba** [sp41mer/BlockchainDevelopmentTutorials#3]
https://github.com/sp41mer/BlockchainDevelopmentTutorials/blob/d267a43050bf62fabc0d6043dba02bea4238e413/MinimalisticICO.sol#L25

**Comment by egorzaremba** [comment]
or its additional warnings

**Comment by sp41mer** [comment]
Что не так с этой строчкой ?

**Comment by egorzaremba** [comment]
cори, все правильно)
